### PR TITLE
CTDA-1281 Add metrics collection to controllers and connectors

### PR DESCRIPTION
**Pull request by DavidGregory084**
Add metrics collection to the controllers and connectors in the API

I have used the convention of using the controller method name in our controllers, and in using `<movement type>-backend-<http method>` in the connectors.

### CODE REVIEW

**Review by RobertLaverick — CHANGES_REQUESTED** [review]
Looks good, one small change - can you change the metric params from magic strings to something defined somewhere?

**Comment by DavidGregory084** [comment]
I think with magic numbers and magic strings, usually we don't like them because they are not self-evident, so it's not apparent why that value was chosen, and they prevent us from changing a value throughout our program if they are reused in multiple places.

I am open to the change but it's additional indirection when searching for the occurrence of a metric - these strings only occur in one place, must be unique and are (hopefully) self-explanatory. Do you think we will get a lot of value out of extracting them as variables @RobertLaverick?

**Comment by RobertLaverick** [comment]
I appreciate the sentiment and its totally sensible. However I'm just cautious of accidental changes to the strings, or the normalisation of magic strings in repos. We're all human and its easy to miss a single character change by accident in a PR, but that then means broken metrics. Further it means we can keep all our metric names in one place, which acts as self-documentation of metrics that we use, as well as silo-ing off the strings so they can't be accidentally changed (and that is exactly the sort of thing that can fail more quietly than we'd expect)

**Comment by DavidGregory084** [comment]
Ok @RobertLaverick I've addressed that - lmk what you think

**Review by RobertLaverick — APPROVED** [review]

**Comment by DavidGregory084** [comment]
@RobertLaverick could you have another quick look? I have added histograms to document the number of arrivals, departures and corresponding messages that are returned by each endpoint. I also have refactored HasMetrics a little bit as some of the code was copied from another project (LocalMetrics) etc. and was not really needed.

**Review by RobertLaverick — APPROVED** [review]

**Pull request merged**
